### ISSUE TITLE
Add an About page to the web application. 

### ISSUE THREAD

**Issue by theinit01** [gdsc-jssstu/CipherBox#11]
Create a simple "About" page in the main HTML file (index.html) and link it from the UI.

**Comment by code-bajju** [comment]
I'd be glad to help you with the "About" page for your open-source project.Please let me know if you have any preferences for particular design components.

**Comment by theinit01** [comment]
@code-bajju, please refer the [Figma file](https://www.figma.com/file/HRAxLh7LUXvFwDYZCaRf7H/Cybersec?type=design&node-id=0-1&mode=design&t=KYTiXyLrb9LlJSW9-0) in the final version of the project section to know how the project should look like.
I am assigning this issue to you.

**Comment by code-bajju** [comment]
<img width="1438" alt="image" src="https://github.com/gdsc-jssstu/CipherBox/assets/104210183/ff5b3da9-17a1-42c5-b3b4-c74aada66fc9">

**Comment by theinit01** [comment]
Looks awesome. Give us a few moments to review all the work.
