### ISSUE TITLE
Add SHA-256 Encryption

### ISSUE THREAD

**Issue by theinit01** [gdsc-jssstu/CipherBox#4]
Create a JavaScript file in the /crypto directory and implement SHA-256 Encryption Algorithm.

#### Resources: 
[SHA-256 Implementations](https://stackoverflow.com/questions/18338890/are-there-any-sha-256-javascript-implementations-that-are-generally-considered-t)
[js-sha256](https://www.npmjs.com/package/js-sha256)

**Comment by RajaVardhan-coder** [comment]
@theinit01 can you please assign this to me

**Comment by theinit01** [comment]
@RajaVardhan-coder, it is assigned to you

**Comment by MAD-vindi** [comment]
@theinit01 hey!!, if no one is working on this currently, can you assign this for me?
