### ISSUE TITLE
Implement AES Algorithm

### ISSUE THREAD

**Issue by theinit01** [gdsc-jssstu/CipherBox#5]
Implement AES algorithm in the aes.js file in /crypto directory.

**Comment by RajaVardhan-coder** [comment]
@theinit01 can you please assign this to me

**Comment by theinit01** [comment]
@RajaVardhan-coder Sure, create a fork and get on the work

**Comment by RajaVardhan-coder** [comment]
@theinit01 can you please check my pull request
